import { useState } from "react"


export const team = [
    {
        id: 1,
        name: "Tsurundede Godswill",
        role: "Project Administrator",
        img: "images/team/prince.png",
        twitter: "https://twitter.com/iknowWassup?s=09",
        linkedin: "https://www.linkedin.com/in/tserundede-godswill-ejueyitchie-5813759a",
    },
    {
        id: 2,
        name: "Isaac J",
        role: "Blockchain Developer",
        img: "images/team/bob.png",
        twitter: "https://twitter.com/Bobman7000",
        linkedin: "https://www.linkedin.com/in/isaac-j-a6764a169",
    },
    {
        id: 3,
        name: "Progress Ojemeh",
        role: "Lead Frontend Engineer",
        img: "images/team/rex.png",
        twitter: "https://www.twitter.com/ojemehprogrex",
        linkedin: "https://www.linkedin.com/in/progress-ojemeh-459730190",
    },
    // {
    //     id: 4,
    //     name: "Uche Justus",
    //     role: "Legal & General Counsel",
    //     img: "images/team/prince.png",
    //     twitter: "",
    //     linkedin: "",
    // },
    {
        id: 5,
        name: "Gbenga Olotu",
        role: "Lead Designer",
        img: "images/team/go.png",
        twitter: "https://twitter.com/oluguzzyman",
        linkedin: "https://www.linkedin.com/in/oluwagbemiga-olotu-a3247710/",
    },
    // {
    //     id: 6,
    //     name: "Adekunle Deji",
    //     role: "Lead Marketer",
    //     img: "images/team/deji.png",
    //     twitter: "https://twitter.com/cool_dejii?t=tguW1YblNbdpQO_V9uVx2Q&s=08",
    //     linkedin: "https://www.linkedin.com/in/deji-adekunle-pmp%C2%AE%C2%A0-mnse-118693118/",
    // },
    {
        id: 7,
        name: "Adediji Steve Adedoyin",
        role: "UI/UX designer",
        img: "images/team/steve.png",
        twitter: "https://twitter.com/adedijicm",
        linkedin: "https://www.linkedin.com/in/adediji-adedoyin-82119577",
    },
    {
        id: 8,
        name: "Muhammad khan",
        role: "Marketer",
        img: "images/team/zee.png",
        twitter: "https://twitter.com/sanaullahk789",
        linkedin: "https://www.linkedin.com/in/zeeshan-niazi-551380166/",
    },
    // {
    //     id: 9,
    //     name: "Muhammad Zeeshan khan",
    //     role: "Marketer",
    //     img: "images/team/zee.png",
    //     twitter: "https://twitter.com/sanaullahk789",
    //     linkedin: "https://www.linkedin.com/in/zeeshan-niazi-551380166/",
    // },
    // {
    //     id: 10,
    //     name: "Ridwan Akinfenwa",
    //     role: "Frontend Engineer",
    //     img: "images/team/go.png",
    //     twitter: "https://twitter.com/Ridwan_Ak00?s=08",
    //     linkedin: "https://www.linkedin.com/in/ridwan-akinfenwa-175b6a1b6",
    // },
    // {
    //     id: 11,
    //     name: "Christain Okeke",
    //     role: "Frontend Engineer",
    //     img: "images/team/go.png",
    //     twitter: "https://www.twitter.com/OkekeChristian_",
    //     linkedin: "https://www.linkedin.com/in/okeke-christian",
    // },
]
