export const profile = [
  {
    id: 0,
    animate: 0.1,
    image: "images/gallery/1.png",
    type: "Main Character",
    name: "King Gui",
  },
  {
    id: 1,
    animate: 0.2,
    image: "images/gallery/2.png",
    type: "Main Character",
    name: "Syndicate Leader Genji",
  },
  {
    id: 2,
    animate: 0.3,
    image: "images/gallery/3.png",
    type: "Main Character",
    name: "The Blood Queen",
  },
  {
    id: 3,
    animate: 0.4,
    image: "images/gallery/4.png",
    type: "Main Character",
    name: "Coalition Spy Han",
  },
  {
    id: 4,
    animate: 0.5,
    image: "images/gallery/5.png",
    type: "Main Character",
    name: "Hired Gun Outlaw",
  },
  {
    id: 5,
    animate: 0.6,
    image: "images/gallery/6.png",
    type: "Main Character",
    name: "Kaya",
  },
  {
    id: 6,
    animate: 0.7,
    image: "images/gallery/7.png",
    type: "Main Character",
    name: "Luna",
  },
  {
    id: 7,
    animate: 0.9,
    image: "images/gallery/8.png",
    type: "Honorary",
    name: "Izu",
  },
  {
    id: 8,
    animate: 0.9,
    image: "images/gallery/9.png",
    type: "Unique",
    name: "Mutant",
  },
  {
    id: 9,
    animate: 1,
    image: "images/gallery/10.png",
    type: "Unique",
    name: "Astronaut",
  },
  {
    id: 10,
    animate: 1.1,
    image: "images/gallery/11.png",
    type: "Uniquer",
    name: "Ninja",
  },
  {
    id: 11,
    animate: 1.2,
    image: "images/gallery/12.png",
    type: "Unique",
    name: "Pandusa",
  },
  {
    id: 12,
    animate: 1.3,
    image: "images/gallery/13.png",
    type: "Uniquer",
    name: "Pimp",
  },
  {
    id: 13,
    animate: 1.4,
    image: "images/gallery/14.png",
    type: "Unique",
    name: "Cyborg",
  }
];
